### ISSUE TITLE
it would be cool to add some examples

### ISSUE THREAD

**Issue by sibelius** [alekbarszczewski/graphql-add-middleware#10]
like this one https://github.com/JCMais/graphql-yup-middleware

https://itnext.io/graphql-mutation-arguments-validation-with-yup-using-graphql-middleware-645822fb748

**Comment by alekbarszczewski** [comment]
Hmm, usage is explained here: https://github.com/alekbarszczewski/graphql-add-middleware#usage.
Not sure what I could add to it... Api is pretty simple, it's one function that takes 2 or 3 args. Please explain what exactly you would like to achieve, maybe I will be able to help :).

**Comment by sibelius** [comment]
having a list of community middlewares provided by the community

so you can just grab one instead of coding the same middleware again

**Comment by alekbarszczewski** [comment]
Well, I don't know any community middlewares based on this package. This package only provides interface to add custom middleware to GraphQL schema.
