### ISSUE TITLE
Build error for TypeScript types

### ISSUE THREAD

**Issue by danielhalodev** [alekbarszczewski/graphql-add-middleware#12]
Hy, thanks for the project.

I noticed the newer versions do not compile, I get these errors.

>        node_modules/graphql-add-middleware/index.d.ts(9,13): error TS2304: Cannot find name 'GraphQLSchema'.
>        node_modules/graphql-add-middleware/index.d.ts(14,13): error TS2304: Cannot find name 'GraphQLSchema'.
>        node_modules/graphql-add-middleware/index.d.ts(18,2): error TS1036: Statements are not allowed in ambient contexts.

Reverted to 0.3.1, works perfectly.

**Comment by alekbarszczewski** [comment]
Thanks for info - will look into this. Recently I added typescript definitions, it seems they don't work as expected.

**Comment by alekbarszczewski** [comment]
@chuckdh Fixed in latest version.
