### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by OliverCole** [alekbarszczewski/graphql-add-middleware#13]
Hi!

I’d love to use this library, but there’s no license specified. Would you mind committing one?

Thanks!

**Comment by OliverCole** [comment]
To clarify, I see “ISC” in `package.json`, but I think Github (and the lawyers) look for an actual license text checked in.

**Comment by alekbarszczewski** [comment]
1. Added LICENSE to repo (MIT)
2. Changed license in package.json to MIT
3. Published new version to npm with license
