### ISSUE TITLE
Doesn't work for Type paths

### ISSUE THREAD

**Issue by kbrandwijk** [alekbarszczewski/graphql-add-middleware#2]
This library works perfectly well for `Query.allPosts` or `Post.title` as path, but it fails for just `Post` as path (for example).

The reason is that it checks if the parent matches here:
https://github.com/alekbarszczewski/graphql-add-middleware/blob/7098b4d999eeba6343e840ff7643167390820ea9/src/graphql-add-middleware.js#L75

But even though that return false, it still continues to add the resolver to every field of every type:
https://github.com/alekbarszczewski/graphql-add-middleware/blob/7098b4d999eeba6343e840ff7643167390820ea9/src/graphql-add-middleware.js#L78-L81
Because matchesField is always true when there's no field specified in the path.

**Comment by alekbarszczewski** [comment]
@kbrandwijk Thanks, I am checking it and as soon I will add test for this case I will merge you PR.

**Comment by alekbarszczewski** [comment]
@kbrandwijk merged and published to npm, thanks!

**Comment by kbrandwijk** [comment]
Thank you for taking care of this so quickly. My framework [qewl](https://github.com/kbrandwijk/qewl) heavily depends on it!
