### ISSUE TITLE
Yarn warning about dependencies

### ISSUE THREAD

**Issue by Cabezaa** [alekbarszczewski/graphql-add-middleware#5]
Hi, first of all, thanks so much for your package, it's great.
When i use this package, and run `yarn` , i got the next message:

``` warning "graphql-add-middleware > graphql-tools@0.10.1" has incorrect peer dependency "graphql@^0.8.0 || ^0.9.0|| ^0.10.0". ```

On my general Package.json, i try to force Yarn to only use one version of Graphql with 

``` 
"resolutions": {
    "graphql": "^0.13.1"
  }
```
But i still got the warning. Any ideas about this? Or maybe, can upgrade the package.json of this library?

Thanks!

**Comment by alekbarszczewski** [comment]
@Cabezaa Thanks,
I upgraded graphql-tools/graphql dependecies to latest versions. Also added yarn.lock file to the repo. Please upgrade graphql-add-middleware to `0.1.4` and let me know if it's ok now :).

**Comment by Cabezaa** [comment]
It's working!

Thanks @alekbarszczewski !

i will close it now :+1:
