### ISSUE TITLE
Passing through props

### ISSUE THREAD

**Issue by eNzyOfficial** [alekbarszczewski/graphql-add-middleware#7]
Hey,

Nice work, and thanks for sharing, would it be possible to implement a way to pass through props?

eg.

`addMiddleware(schema, 'Query', 'permission:create-users', permissionMiddlewareFn);`

Resolving to something like:

`async (middleware, root, args, context, info, next, permission) => { // Where permission = create-users }`

or 

`async (middleware, root, args, context, info, next,) => {  //  Where args.permission = create-users }`

**Comment by alekbarszczewski** [comment]
Hey, I am not sure what exactly you want to achieve? You can always pass some data through `context` (read about context here http://graphql.org/learn/execution/#root-fields-resolvers and here https://github.com/graphql/express-graphql#options). `context` is set once per GraphQL query/mutation and is passed to every middleware and resolver.

If you want to set some data in a middleware that would be visible to resolvers you can also use context:

```js
addMiddleware(schema, async (root, args, context, info, next) => {
  // context will be passed to all middleware after this one and also to all GraphQL resolvers
  // you just have to ensure that initial context is not null
  context.permissions = { createUsers: true }
  return await next()
})

addMiddleware(schema, 'Mutation.createUser', async (root, args, context, info, next) => {
  if (!context.permissions.createUsers) {
    throw new Error('You are not allowed to create users')
  }
  return await next()
})
``` 

`context` is often used to pass user session to GraphQL resolvers.

**Comment by eNzyOfficial** [comment]
Hey,

I'll use [Spatie Permissions](https://github.com/spatie/laravel-permission) as a better example, you have one piece of middleware to handle permission/role checking, which is done by passing in props at build-time, this way you don't have to create N pieces of middleware for each subset of permission/role checking.

Most frameworks with middleware support this feature and I have been scouring around trying to find a decent middleware solution for graphql (but seem to be a lack of), this package offers basically everything I'm after with the exception of passing in props.

I'm hoping this makes more sense!

**Comment by alekbarszczewski** [comment]
@eNzyOfficial Sorry I still don't understand :). If you want to pass some props to middleware at build time just wrap it in higher order function, for example:

```js
const authMiddleware = props => (root, args, context, info, text) => {
  if (!props.createUsers) {
    // do something
  }
}

addMiddleware(schema, 'Mutation.createUser', authUser(props)) 
```

Anyway, this Spatie Permissions is some PHP library. Maybe https://www.npmjs.com/package/casl is what you are looking for:

```js
app.use('/graphql', graphqlHTTP(async (req, res, graphQLParams) => {
  const user = req.session.user
  const ability = AbilityBuilder.define((can, cannot) => {
    if (user.role === 'admin') {
      can('create', 'User')
    }
  })
  return {
    schema: MyGraphQLSchema,
    context: { ablity }
  }
}));

// resolver in your schema
async (root, args, context, info, next) => {
  if (!context.ability.can('create', 'Post')) {
    throw new Error('not authorized')
  }
}
```

**Comment by eNzyOfficial** [comment]
I'll try that out, apologies, my javascript isn't amazing, I come from strongly typed languages so I'm still getting my head around certain ways to do things, I wasn't aware you could double => and have it work like that so I suppose that's on me ahaha! I'm so used to having to pass in parameters explicitly!

I've already built my permissions system but thanks for the link, I'll check that out next time I need to use permissions!

Again, thanks for the help and pointing out my stupidities ahaha!
