### ISSUE TITLE
How can i get request in middleware for all resovlers?

### ISSUE THREAD

**Issue by Artawower** [alekbarszczewski/graphql-add-middleware#9]
I want to enable an authentication using  JWT to my GraphQL API. How can I access to the request object from addMiddleware?
```
 addMiddleware(sch, async function (root, args, context, info, next) {
        // you can modify root, args, context, info
        console.log(request.body.token) // How can i get request?
        const result = await next();
        return result; // you must return value
    }); 
```

**Comment by alekbarszczewski** [comment]
If you are using express.js you probably also use [express-graphql](https://github.com/graphql/express-graphql). By default express-graphql passes request as graphql context (see context option description https://github.com/graphql/express-graphql#options). So if you will set request as context then you can do:

```js
addMiddleware(sch, async function (root, args, context, info, next) {
        // you can modify root, args, context, info
        console.log(context.body.token) // <----------------------
        const result = await next();
        return result; // you must return value
    }); 
```
